name: deploy
description: download artifacts by name, s3 sync to bucket, cf invalidate
inputs:
  region:  # id of input
    description: 'Aws region the S3 bucket is located'
    required: true
    default: 'us-west-2'
  env:  # id of input
    description: 'environment to build'
    required: true
  bucket:
    description: 'AWS S3 Bucket to host the website'
    required: true
  artifact_name:
    description: 'Built artifact of frontend assets'
    required: true
runs:
  using: "composite"
  steps:
    # Deploy to s3
    - name: Sync with S3
      shell: bash
      run: |
        cd build
        aws s3 sync . s3://${{ input.artifact_name }}
    # Invalidate Cloudfront
    - name: Invalidate Cloudfront
      shell: bash
      run: |
        export DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?@=='${{ input.bucket }}']].Id | [0]" | tr -d '"')
        aws cloudfront create-invalidation --distribution-id ${DIST_ID} --paths "/*"