name: Pull request
on:
  pull_request:
    branches: ['*']
# Jobs
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CI: true
      build_env: production
    steps:
    - uses: actions/checkout@v2
    - name: Run Lint
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: |
        yarn
        yarn lint
  unit-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      build_env: production
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: |
        yarn
        yarn test --watchAll=false